name: pizza-voc-analysis-app
description: "AI-powered pizza company customer feedback analysis"

command:
  - streamlit
  - run
  - app.py
  - --server.port=8000
  - --server.address=0.0.0.0
  - --server.headless=true
  - --logger.level=info
  - --server.enableCORS=false
  - --server.enableXsrfProtection=false

env:
  - name: STREAMLIT_SERVER_PORT
    value: "8000"
  - name: STREAMLIT_SERVER_ADDRESS
    value: "0.0.0.0"
  - name: STREAMLIT_LOGGER_LEVEL
    value: "info"

  # Required for all Databricks SDK calls / OBO
  - name: DATABRICKS_HOST
    value: e2-demo-field-eng.cloud.databricks.com

  # Vector Search (used by the search panel)
  - name: VECTOR_SEARCH_ENDPOINT
    value: users.kevin_ippen.voc_chunks_index
  - name: VECTOR_INDEX_NAME
    value: users.kevin_ippen.voc_pizza_chunks_for_index

  # Optional: LLM summary (omit if you don’t need summaries yet)
  - name: LLM_ENDPOINT
    value: databricks-gpt-oss-20b

  # For the “OBO Test” section
  - name: SQL_WAREHOUSE_HTTP_PATH
    value: /sql/1.0/warehouses/<your-warehouse-id>
