name: pizza-voc-analysis-app
description: "AI-powered pizza company customer feedback analysis"

command:
  - streamlit
  - run
  - app.py
  - --server.port=8000
  - --server.address=0.0.0.0
  - --server.headless=true
  - --logger.level=info
  - --server.enableCORS=false
  - --server.enableXsrfProtection=false

# Optional runtime resources for the container (not cluster sizing)
# You can remove this block if you don't need explicit limits.
# resources:
#   memory: "2Gi"
#   cpu: "1000m"

env:
  - name: STREAMLIT_SERVER_PORT
    value: "8000"
  - name: STREAMLIT_SERVER_ADDRESS
    value: "0.0.0.0"
  - name: STREAMLIT_LOGGER_LEVEL
    value: "info"