name: pizza-voc-analysis-app
description: "AI-powered pizza company customer feedback analysis"

command:
  - streamlit
  - run
  - app.py
  - --server.port=8000
  - --server.address=0.0.0.0
  - --server.headless=true
  - --logger.level=info
  - --server.enableCORS=false
  - --server.enableXsrfProtection=false

env:
  - name: STREAMLIT_SERVER_PORT
    value: "8000"
  - name: STREAMLIT_SERVER_ADDRESS
    value: "0.0.0.0"
  - name: STREAMLIT_LOGGER_LEVEL
    value: "info"

  - name: DATABRICKS_HOST
    value: https://e2-demo-field-eng.cloud.databricks.com

  - name: VECTOR_SEARCH_ENDPOINT
    value: dbdemos_vs_endpoint
  - name: VECTOR_INDEX_NAME
    value: users.kevin_ippen.voc_chunks_index   # <= fix if different

  - name: LLM_ENDPOINT
    value: databricks-gpt-oss-20b

  - name: DATABRICKS_AUTH_TYPE
    value: oauth-m2m